# This is a basic workflow to help you get started with Actions

name: php work api

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install zip
      - name: Run a one-line script
        run: df -h
      # Runs a set of commands using the runners shell
      - name: 下载
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ----------------
          # wget -i url.txt
          sudo chmod -R 777 /mnt
          mkdir /mnt/data
          cd /mnt/data
          #wget https://file2.yuuki.me/d/Public/GD1/Project/GenshinImpact/Data/Android/3.2.0/Global/Part/com.miHoYo.ys.x.zip?sign=rULzu6rvVoZnfPbjNyevPmnqD9qw2mYNjogKugIGvQU=:0 -O com.miHoYo.ys.x.zip
          #wget https://file2.yuuki.me/d/Public/GD1/Project/GenshinImpact/Data/Android/3.2.0/Global/Part/com.miHoYo.ys.x.z01?sign=judN5E6iiYM8VQa2cySbbvEtv5AvnHO9m9Nso659w6g=:0 -O com.miHoYo.ys.x.z01
          #wget https://file2.yuuki.me/d/Public/GD1/Project/GenshinImpact/Data/Android/3.2.0/Global/Part/com.miHoYo.ys.x.z02?sign=s0AoEVNejtSn14NMpahou75wjbFEP4RUIIIVJUo_vAY=:0 -O com.miHoYo.ys.x.z02
          #wget https://file2.yuuki.me/d/Public/GD1/Project/GenshinImpact/Data/Android/3.2.0/Global/Part/com.miHoYo.ys.x.z03?sign=hpXWN6LbFXyyN0nEConWpKqUvRGj0pA5ZCyU9sElb1c=:0 -O com.miHoYo.ys.x.z03
          wget https://file2.yuuki.me/d/Public/GD1/Project/GenshinImpact/Data/Android/3.2.0/Global/Part/com.miHoYo.ys.x.z04?sign=PgNc2LANJNi9Q1xQvm-E2FrMZnxri0j-jtXbc4anahw=:0 -O com.miHoYo.ys.x.z04
          #git clone https://chromium.googlesource.com/external/github.com/llvm/llvm-project.git
          echo ----------------
          
      - name: 打包
        run: zip -r /mnt/download.zip /mnt/data/
      - name: 上传 # 上传构建产物，这里我们的源码目录是 src，而实际运行的代码是构建后的 bin 目录
        uses: actions/upload-artifact@v2
        with:
          name: download_output
          path: /mnt/download.zip
